#!/usr/bin/env bash


DOTFILES_DIR="$HOME/Documents/dotfiles"

printf "Installing packages from Homebrew...\n"

# make sure brew.txt exists
if [ ! -f $DOTFILES_DIR/brew/Brewfile ]; then
    printf "Installation stopped: Brewfile not found.\n"
    exit
fi

# install packages
(cd $DOTFILES_DIR/brew && brew bundle)
