#!/usr/bin/env bash


DOTFILES_DIR="$HOME/Documents/dotfiles"

printf "Installing packages from Homebrew...\n"

# make sure brew.txt exists
if [ ! -f $DOTFILES_DIR/misc/brew.txt ]; then
    printf "Installation stopped: misc/brew.txt not found.\n"
    exit
fi

# install packages
brew install $(cat $DOTFILES_DIR/misc/brew.txt)
