#!/usr/bin/env bash


printf "\nCleaning up home...\n\n"

# remove unnecessary files in home directory
if [ -f $HOME/.viminfo ]; then
    rm $HOME/.viminfo
fi

# clean up vim undo files
find $HOME/.local/share/nvim/undo -type f -mtime +90 -delete
