#!/usr/bin/env bash


printf "\nCleaning up home...\n\n"

# remove unnecessary files in home directory
if [ -f $HOME/.viminfo ]; then
    rm $HOME/.viminfo
fi

if [ -f $HOME/.python_history ]; then
    rm $HOME/.python_history
fi

if [ -f $HOME/.lesshst ]; then
    rm $HOME/.lesshst
fi

# clean up vim undo files
find $HOME/.vim/undo -type f -mtime +90 -delete
