#!/usr/bin/env bash


T='aBc'

echo -e "\n         40m     41m     42m     43m     44m     45m     46m     47m"

colors=(
    '    m'
    '   1m'
    '  30m'
    '1;30m'
    '  31m'
    '1;31m'
    '  32m'
    '1;32m'
    '  33m'
    '1;33m'
    '  34m'
    '1;34m'
    '  35m'
    '1;35m'
    '  36m'
    '1;36m'
    '  37m'
    '1;37m'
)

for color in "${colors[@]}"; do
    FG=${color// /}
    echo -en "\033[$FG $color"

    for background_color in 40m 41m 42m 43m 44m 45m 46m 47m; do
        echo -en "$EINS \033[$FG\033[$background_color  $T  \033[0m"
    done
    echo
done
echo
