#!/usr/bin/env python3

"""
A quick test run for new fonts.

"""


def display_text(text, form):
    """
    Display the text.

    Args:
        text (str): the text to be displayed
        form (int): 0 for standard, 1 for italics

    """

    if form == 0:
        print(text)
    elif form == 1:
        print('\033[3m' + text + '\033[0m')
    else:
        print('Invalid form.')


if __name__ == '__main__':
    """
    Main driver

    """

    text = """\
    ABCDEFGHIJKLMNOPQRSTUVWXYZ
    abcdefghijklmnopqrstuvwxyz
    1234567890 !@#$%^&* <=<>=>
    ~~==__--++ :; "'` ,. ? /|\
    B80O9 LIil17 5Ss2Zz ({[]})
    """

    print()
    display_text(text, 0)
    display_text(text, 1)
