#!/usr/bin/env python3

"""
A quick test run for new fonts.

"""


if __name__ == '__main__':
    text = """
    ABCDEFGHIJKLMNOPQRSTUVWXYZ
    abcdefghijklmnopqrstuvwxyz
    1234567890 !@#$%^&* <=<>=>
    ~~==__-- :; "'` ,. ? /|\ +
    B80O9 LIil17 5Ss2Zz ({[]})\
    """

    # print normally
    print(text)

    # switch to italics and print again
    print('\033[3m')
    print(text)

    # switch back to standard text
    print('\033[0m')
