#!/usr/bin/env python3

txt = """
ABCDEFGHIJKLMNOPQRSTUVWXYZ
abcdefghijklmnopqrstuvwxyz
1234567890 !@#$%^&* <=<>=>
~~==__-- :; "'` ,. ? /|\ +
B80O9 LIil17 5Ss2Zz ({[]})
"""

print(txt.strip())
print('\033[3m')
print(txt.strip())
print('\033[0m')
