#!/usr/bin/env python3

"""
A simple game of hangman.

"""

import random

# TODO: Retrieve words using some online API.
# TODO: Figure out how many lives to allow.

def display_word(word):
    """
    Display the word in the correct format for the guessing game.

    Args:
        word (list): list of tuples, where each tuple indicates a letter
            in the word and whether or not that letter has been guessed

    Return:
        int: number of unguessed letters left

    """

    string = ''

    for letter in word:
        if letter[1]:
            string += letter[0]
        else:
            string += '_'
        string += ' '

    print(string)
    return string.count('_')


def play(wb, lives=5):
    """
    Start a word guessing game using words from a provided word bank.

    Args:
        wb (list): list of words that can be used
        lives (int): number of lives the user starts with

    """

    print('You are starting with {} lives.'.format(lives))

    # get random word from list
    rand_i = random.randint(0, len(wb) - 1)
    word = wb[rand_i]

    # chosen word is stored as a list of tuples in the form:
    # (letter (str), guessed (bool))
    status = [(letter, False) for letter in word]
    display_word(status)

    # create set used to track which letters haved been guessed
    guessed = set()

    while True:
        guess = input('Guess a letter: ')

        if guess == '!':
            print('The word was {}. Goodbye!'.format(word.upper()))
            return
        elif len(guess) > 1 or guess.isalpha() == False:
            print('Invalid guess. Try again.')
        elif guess in guessed:
            print('Letter already guessed. Try again.')
        else:
            guessed.add(guess)

            # check guess
            if guess in word:
                status = [(lt[0], lt[0] in guessed) for lt in status]
                print('Correct!')
            else:
                lives -= 1

                # exit when out of lives
                if lives < 1:
                    print('Sorry, you have run out of lives.')
                    print('The word was {}'.format(word.upper()))
                    return
                else:
                    print('Incorrect. {} lives remaining'.format(lives))

            if display_word(status) == 0:
                print('You solved it with {} lives remaining!'.format(lives))
                return


if __name__ == '__main__':
    """
    Program driver

    """

    temp_wordbank = ['cat', 'dog', 'fish', 'pig', 'cow']

    print("Let's play hangman! Enter ! at any time to exit.")
    play(temp_wordbank)
