#!/usr/bin/env bash


DOTFILES_DIR="$HOME/Documents/dotfiles"

printf "Installing packages from PyPI...\n"

# make sure pip.txt exists
if [ ! -f $DOTFILES_DIR/packages/pip.txt ]; then
    printf "Installation stopped: packages/pip.txt not found.\n"
    exit
fi

# install packages
python3 -m pip install -r $DOTFILES_DIR/packages/pip.txt --user >/dev/null
