#!/usr/bin/env bash


DOTFILES_DIR="$HOME/Documents/dotfiles"
STOW_DIR="$DOTFILES_DIR/stow"

printf "\nInstalling dotfiles to home directory...\n"

# create directories if necessary
printf "\nCreating missing directories...\n"

for dir in $(find $STOW_DIR -type d); do
    dir_to_create=${dir/$STOW_DIR/"$HOME"}

    if [ ! -d $dir_to_create ]; then
        echo $dir_to_create
        mkdir $dir_to_create
    fi
done

# create backups directory
printf "\nCreating backups...\n"

if [ ! -d "$DOTFILES_DIR/.backups" ]; then
    mkdir $DOTFILES_DIR/.backups
fi

# look for any files that could cause issues with stow and make backups
for stow_file in $(find $STOW_DIR -type f); do
    file_to_move=${stow_file/$STOW_DIR/"$HOME"}

    if [ -f $file_to_move ]; then
        echo $file_to_move
        mv $file_to_move $DOTFILES_DIR/.backups
    fi
done

# stow dotfiles
printf "\nStowing files...\n"

(cd $DOTFILES_DIR; stow -t $HOME stow)

printf "Done.\n"

